### ISSUE TITLE
[FEAT]: make the languages section a holistic donut

### ISSUE THREAD

**Issue by emoral435** [emoral435/Portfolio#15]
**Summary for the change**
Instead of just displaying the languages, also include a donut that represents the amount of the lanuage used! I am pretty sure that is included in the GitHub GraphQL api.... If not, then this gets instantly resolved!

**Motivation for the change**
* It would match our github readme

**Tasks**
- [ ] See if the percentage of the language used is offered in the API
- [ ] Update the API key if need be by changing out request
- [ ] style a donut of that percentage
- [ ] see what makes sense on reducing the shared look between the topics and languages section

**Related issues / links**
* N/A

**Comment by emoral435** [comment]
Not useful for the current layout of the website, and I don't think this would mesh well with the current style! Closing.
