### ISSUE TITLE
[FEAT]: add Nextcloud experience

### ISSUE THREAD

**Issue by emoral435** [emoral435/Portfolio#16]
**Summary for the change**
With our time at Nextcloud being done (for now, planning on rejoining if academics allow), update personal portfolio to reflect marks achieved

**Motivation for the change**
* Better showcase skills attained and demonstrated during internship

**Tasks**
- [ ] Copy over bullet points from resume\
- [ ] Update the download resume button
- [ ] Perhaps include a section where we link a summary about our time at Nextcloud?

**Related issues / links**
* N/A
