### ISSUE TITLE
[STYLING] BIG STYLISTIC CHANGES TO MAKE

### ISSUE THREAD

**Issue by emoral435** [emoral435/Portfolio#6]
**Summary for the change**
To migrate to V2, it is best if we make all the small collection of stylistic choices within one PR so that we do not repeat building too much

**Motivation for the change**
* FOR DISTINCTION ON THE LAST VERSION >:)

**Tasks**
- [x] Make the download resume button the only thing non-text item in our about me
- [x] add a picture of our cats within our about me (?) (NOT ADDED)
- [x] Make the experience section more visually appealing
    - Make a separate component with easier data integration functionalities ( like using objects, separate folders etc.)
    - Add a section that is not just bullet points
    - Each component should have a section for the company logo, their website, bullet points of what I did, an informal section where I talk about what I did
 
- [x] Improve project section styling, but instead of the experience side potentially growing, make the projects section more condensed now that we have more experience
- [x] Change the picture to be something more friendly but still professional

**Related issues / links**
* #5
